// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rent_a_car.Models;

#nullable disable

namespace rent_a_car.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250625110942_UpdateSeedForElectricCars")]
    partial class UpdateSeedForElectricCars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("rent_a_car.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PricePerDay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Seats")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transmission")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Economy",
                            Description = "Compact and fuel-efficient, perfect for city driving.",
                            Engine = "1.2L",
                            FuelType = "Petrol",
                            ImageUrl = "/img/opel-corsa-54390.webp",
                            Model = "Opel Corsa",
                            PricePerDay = "35",
                            Seats = "5",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Standard",
                            Description = "Reliable and comfortable sedan, great for daily use.",
                            Engine = "1.5L",
                            FuelType = "Diesel",
                            ImageUrl = "/img/astra-54407.webp",
                            Model = "Opel Astra",
                            PricePerDay = "45",
                            Seats = "5",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Luxury",
                            Description = "Powerful sports car with impressive performance and style.",
                            Engine = "2.0L",
                            FuelType = "Petrol",
                            ImageUrl = "/img/mercedes-c-200-48693.webp",
                            Model = "Mercedes C200",
                            PricePerDay = "65",
                            Seats = "5",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Luxury",
                            Description = "Powerful sports car with impressive performance and style.",
                            Engine = "2.0L",
                            FuelType = "Diesel",
                            ImageUrl = "/img/320i-56645.webp",
                            Model = "BMW 320i",
                            PricePerDay = "75",
                            Seats = "5",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 5,
                            Category = "SUV",
                            Description = "Spacious and versatile SUV, perfect for family trips.",
                            Engine = "1.6L",
                            FuelType = "Diesel",
                            ImageUrl = "/img/nwqash-64376.webp",
                            Model = "Nissan Qashqai",
                            PricePerDay = "55",
                            Seats = "5",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 6,
                            Category = "SUV",
                            Description = "Compact crossover with excellent fuel economy.",
                            Engine = "1.0L",
                            FuelType = "Petrol",
                            ImageUrl = "/img/bayon.webp",
                            Model = "Hyundai Bayon",
                            PricePerDay = "45",
                            Seats = "5",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Economy",
                            Description = "Stylish and agile hatchback, ideal for city driving.",
                            Engine = "1.0L",
                            FuelType = "Petrol",
                            ImageUrl = "/img/clio2024-55893.webp",
                            Model = "Renault Clio",
                            PricePerDay = "30",
                            Seats = "5",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Economy",
                            Description = "Efficient and affordable electric sedan with modern technology.",
                            Engine = "Electric",
                            FuelType = "Electric",
                            ImageUrl = "/img/tesla-model-3.png",
                            Model = "Tesla Model 3",
                            PricePerDay = "60",
                            Seats = "5",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Standard",
                            Description = "Popular electric hatchback, perfect for city and daily use.",
                            Engine = "Electric",
                            FuelType = "Electric",
                            ImageUrl = "/img/nissan-leaf.png",
                            Model = "Nissan Leaf",
                            PricePerDay = "55",
                            Seats = "5",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Luxury",
                            Description = "High-performance luxury electric sedan with cutting-edge features.",
                            Engine = "Electric",
                            FuelType = "Electric",
                            ImageUrl = "/img/porsche-taycan.png",
                            Model = "Porsche Taycan",
                            PricePerDay = "120",
                            Seats = "5",
                            Transmission = "Automatic"
                        });
                });

            modelBuilder.Entity("rent_a_car.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Admin User",
                            IsAdmin = true,
                            PasswordHash = "73l8gRjwLftklgfdXT+MdiMEjJwGPVMsyVxe16iYpk8=",
                            Username = "admin@site.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
