// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rent_a_car.Models;

#nullable disable

namespace rent_a_car.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250624110213_SeedAdminUser")]
    partial class SeedAdminUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("rent_a_car.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PricePerDay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Seats")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transmission")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Economy",
                            Description = "Compact and fuel-efficient, perfect for city driving.",
                            ImageUrl = "/img/opel-corsa-54390.webp",
                            Model = "Opel Corsa",
                            PricePerDay = "35"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Standard",
                            Description = "Reliable and comfortable sedan, great for daily use.",
                            ImageUrl = "/img/astra-54407.webp",
                            Model = "Opel Astra",
                            PricePerDay = "45"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Luxury",
                            Description = "Powerful sports car with impressive performance and style.",
                            ImageUrl = "/img/mercedes-c-200-48693.webp",
                            Model = "Mercedes C200",
                            PricePerDay = "65"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Luxury",
                            Description = "Powerful sports car with impressive performance and style.",
                            ImageUrl = "/img/320i-56645.webp",
                            Model = "BMW 320i",
                            PricePerDay = "75"
                        },
                        new
                        {
                            Id = 5,
                            Category = "SUV",
                            Description = "Spacious and versatile SUV, perfect for family trips.",
                            ImageUrl = "/img/nwqash-64376.webp",
                            Model = "Nissan Qashqai",
                            PricePerDay = "55"
                        },
                        new
                        {
                            Id = 6,
                            Category = "SUV",
                            Description = "Compact crossover with excellent fuel economy.",
                            ImageUrl = "/img/bayon.webp",
                            Model = "Hyundai Bayon",
                            PricePerDay = "45"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Economy",
                            Description = "Stylish and agile hatchback, ideal for city driving.",
                            ImageUrl = "/img/clio2024-55893.webp",
                            Model = "Renault Clio",
                            PricePerDay = "30"
                        });
                });

            modelBuilder.Entity("rent_a_car.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Admin User",
                            IsAdmin = true,
                            PasswordHash = "n4bQgWbL8zA1Q9Qf8rQJvQw8Qw8Qw8Qw8Qw8Qw8Qw8Qw=",
                            Username = "admin@site.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
