// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rent_a_car.Models;

#nullable disable

namespace rent_a_car.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260916062344_AddReservationsAndDecimalPricing")]
    partial class AddReservationsAndDecimalPricing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("rent_a_car.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seats")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transmission")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Economy",
                            Description = "Compact and fuel-efficient, perfect for city driving.",
                            Engine = "1.2L",
                            FuelType = "Petrol",
                            ImageUrl = "/img/opel-corsa-54390.webp",
                            Model = "Opel Corsa",
                            PricePerDay = 35m,
                            Seats = "5",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Standard",
                            Description = "Reliable and comfortable sedan, great for daily use.",
                            Engine = "1.5L",
                            FuelType = "Diesel",
                            ImageUrl = "/img/astra-54407.webp",
                            Model = "Opel Astra",
                            PricePerDay = 45m,
                            Seats = "5",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Luxury",
                            Description = "Powerful sports car with impressive performance and style.",
                            Engine = "2.0L",
                            FuelType = "Petrol",
                            ImageUrl = "/img/mercedes-c-200-48693.webp",
                            Model = "Mercedes C200",
                            PricePerDay = 65m,
                            Seats = "5",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Luxury",
                            Description = "Powerful sports car with impressive performance and style.",
                            Engine = "2.0L",
                            FuelType = "Diesel",
                            ImageUrl = "/img/320i-56645.webp",
                            Model = "BMW 320i",
                            PricePerDay = 75m,
                            Seats = "5",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 5,
                            Category = "SUV",
                            Description = "Spacious and versatile SUV, perfect for family trips.",
                            Engine = "1.6L",
                            FuelType = "Diesel",
                            ImageUrl = "/img/nwqash-64376.webp",
                            Model = "Nissan Qashqai",
                            PricePerDay = 55m,
                            Seats = "5",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 6,
                            Category = "SUV",
                            Description = "Compact crossover with excellent fuel economy.",
                            Engine = "1.0L",
                            FuelType = "Petrol",
                            ImageUrl = "/img/bayon.webp",
                            Model = "Hyundai Bayon",
                            PricePerDay = 45m,
                            Seats = "5",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Economy",
                            Description = "Stylish and agile hatchback, ideal for city driving.",
                            Engine = "1.0L",
                            FuelType = "Petrol",
                            ImageUrl = "/img/clio2024-55893.webp",
                            Model = "Renault Clio",
                            PricePerDay = 30m,
                            Seats = "5",
                            Transmission = "Manual"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Economy",
                            Description = "Efficient and affordable electric sedan with modern technology.",
                            Engine = "Electric",
                            FuelType = "Electric",
                            ImageUrl = "/img/teslamodel3.webp",
                            Model = "Tesla Model 3",
                            PricePerDay = 60m,
                            Seats = "5",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Standard",
                            Description = "Popular electric hatchback, perfect for city and daily use.",
                            Engine = "Electric",
                            FuelType = "Electric",
                            ImageUrl = "/img/nissanleaf.webp",
                            Model = "Nissan Leaf",
                            PricePerDay = 55m,
                            Seats = "5",
                            Transmission = "Automatic"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Luxury",
                            Description = "High-performance luxury electric sedan with cutting-edge features.",
                            Engine = "Electric",
                            FuelType = "Electric",
                            ImageUrl = "/img/taycan.webp",
                            Model = "Porsche Taycan",
                            PricePerDay = 120m,
                            Seats = "5",
                            Transmission = "Automatic"
                        });
                });

            modelBuilder.Entity("rent_a_car.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("rent_a_car.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Admin User",
                            IsAdmin = true,
                            PasswordHash = "100000.+NGnHDwdkXxNBanGaNOGqA==.9gwtfQO5sYtd2jnQpVZkYQt2xZUsz3HJOn9njIRWEhM=",
                            Username = "admin@site.com"
                        });
                });

            modelBuilder.Entity("rent_a_car.Models.Reservation", b =>
                {
                    b.HasOne("rent_a_car.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rent_a_car.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
